include: package:flutter_lints/flutter.yaml

linter:
  rules:
    #Enabled
    avoid_print: true
    always_specify_types: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    prefer_const_constructors: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true
    unnecessary_this: true
    sort_constructors_first: true
    prefer_const_literals_to_create_immutables: true
    avoid_init_to_null: true
    type_annotate_public_apis: true
    always_put_control_body_on_new_line: true
    always_use_package_imports: true
    avoid_annotating_with_dynamic: true
    avoid_escaping_inner_quotes: true
    avoid_final_parameters: true
    avoid_multiple_declarations_per_line: true
    avoid_type_to_string: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    empty_catches: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    file_names: true
    no_duplicate_case_values: true
    no_literal_bool_comparisons: true
    no_leading_underscores_for_local_identifiers: true
    no_self_assignments: true
    prefer_conditional_assignment: true
    prefer_double_quotes: true
    prefer_equal_for_default_values: true
    prefer_expression_function_bodies: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_breaks: true
    unnecessary_const: true
    unnecessary_late: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_string_escapes: true
    unnecessary_raw_strings: true
    unnecessary_parenthesis: true
    unnecessary_string_interpolations: true
    unnecessary_to_list_in_spreads: true
    unnecessary_underscores: true
    use_named_constants: true

    #Disabled
    non_constant_identifier_names: false
    sized_box_for_whitespace: false