// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiWsQj21FL1f1VePwm4WgvOp5lnPZqlJc',
    appId: '1:373107998814:web:70dafb376e634a5b1774cf',
    messagingSenderId: '373107998814',
    projectId: 'semo-5557f',
    authDomain: 'semo-5557f.firebaseapp.com',
    storageBucket: 'semo-5557f.appspot.com',
    measurementId: 'G-BQNWRHH5ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhE5EUKt2eYHf8ZaUvJOcteEeMaXNoqQs',
    appId: '1:373107998814:android:a963cce13fa1e1521774cf',
    messagingSenderId: '373107998814',
    projectId: 'semo-5557f',
    storageBucket: 'semo-5557f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrPZQX13oDeINjnMgCmX6zystuPUKdtUQ',
    appId: '1:373107998814:ios:5c6b968e1a1314291774cf',
    messagingSenderId: '373107998814',
    projectId: 'semo-5557f',
    storageBucket: 'semo-5557f.appspot.com',
    iosBundleId: 'net.examnet.semo',
  );
}
